import { Space_Grotesk } from "next/font/google";

import { type Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import '@/styles/globals.css';


export const metadata: Metadata = {
  title: "Crowd fund",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const space = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${space.className}`}>
      <AntdRegistry>
        <body>{children}</body>
      </AntdRegistry>
    </html>
  );
}
